// docs/controllers/roles.http

# 5. Crear la tabla de userRoles()  CRUD COMPLETO (crear, obtener, eliminar y actualizar)
@baseUrl = http://localhost:3001

#Crear nuevo rol
POST {{baseUrl}}/api/roles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzMzMwNjcyLCJleHAiOjE3MzMzMzQyNzJ9._15YTO-nyOss7wgifgF_qdYI59JiGyESV8efOGC3VCw
{
    "roleName": "USUARIO"
}

#Obtener todo
GET {{baseUrl}}/api/roles

# Obtener rol por ID
GET {{baseUrl}}/api/roles/1

#Obtener rol por nombre
GET {{baseUrl}}/api/roles/name/ADMIN

#Obtener cantidad total de roles
GET {{baseUrl}}/api/roles/count

#Actualizar un rol
PUT {{baseUrl}}/api/roles/1
Content-Type: application/json
Authorization: Bearer tu_token_aqui

{
    "roleName": "SUPER_ADMIN"
}

# Eliminar un rol
DELETE {{baseUrl}}/api/roles/1
Authorization: Bearer tu_token_aqui